In [3]:
import pandas as pd
import numpy as np

In [4]:
import warnings
warnings.filterwarnings("ignore")

## 0. An end-to-end Sklearn workflow

In [5]:
# 1. Get data to ready

heart_disease = pd.read_csv("../../data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
# Create features matrix
x = heart_disease.iloc[:,:-1]
# Create labels 
y = heart_disease["target"]

In [7]:
#2. Choose the right model and hyperparameter
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
# We'll keep the default hyperparameter
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [8]:
#3. Fit model to data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=10, train_size=0.8, shuffle=True)

In [9]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [10]:
#4. make a prediction
y_predict = clf.predict(x_test)
y_predict

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1])

In [11]:
#4. Evaluate the model on the training data and test data
clf.score(x_train,y_train)

1.0

In [12]:
clf.score(x_test,y_test)

0.7868852459016393

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.84      0.77      0.81        35
           1       0.72      0.81      0.76        26

    accuracy                           0.79        61
   macro avg       0.78      0.79      0.78        61
weighted avg       0.79      0.79      0.79        61



In [14]:
pd.DataFrame(confusion_matrix(y_test, y_predict), columns=["0","1"], index=["0","1"])


0   1
0  27   8
1   5  21

In [15]:
accuracy_score(y_test,y_predict)

0.7868852459016393

In [16]:
#5. Improve model
# Try diffenrent amount of n_estimators
np.random.seed(42)
for i in range(10,100,10) : 
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print(f"Model accuracy test set with {i} estimators : {clf.score(x_test, y_test)*100:.2f}%")

Model accuracy test set with 10 estimators : 81.97%
Model accuracy test set with 20 estimators : 81.97%
Model accuracy test set with 30 estimators : 81.97%
Model accuracy test set with 40 estimators : 80.33%
Model accuracy test set with 50 estimators : 81.97%
Model accuracy test set with 60 estimators : 80.33%
Model accuracy test set with 70 estimators : 78.69%
Model accuracy test set with 80 estimators : 78.69%
Model accuracy test set with 90 estimators : 77.05%


In [18]:
#6. Save model and load it
import pickle 
pickle.dump(clf, open("../../models/random-forest-model-1.pkl","wb"))

In [19]:
loaded_model = pickle.load(open("../../models/random-forest-model-1.pkl", "rb"))
loaded_model.score(x_test,y_test)

0.7704918032786885

In [21]:
loaded_model.predict(x_test)

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1])

In [23]:
## 0. An end-to-end Sklearn workflow

# 1. Get data to ready

heart_disease = pd.read_csv("../../data/heart-disease.csv")
heart_disease.head()

# Create features matrix
x = heart_disease.iloc[:,:-1]
# Create labels 
y = heart_disease["target"]

#2. Choose the right model and hyperparameter
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
# We'll keep the default hyperparameter
clf.get_params()

#3. Fit model to data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=10, train_size=0.8, shuffle=True)

clf.fit(x_train,y_train)

#4. make a prediction
y_predict = clf.predict(x_test)
y_predict

#4. Evaluate the model on the training data and test data
clf.score(x_train,y_train)

clf.score(x_test,y_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test,y_predict))

pd.DataFrame(confusion_matrix(y_test, y_predict), columns=["0","1"], index=["0","1"])


accuracy_score(y_test,y_predict)

#5. Improve model
# Try diffenrent amount of n_estimators
np.random.seed(42)
for i in range(10,100,10) : 
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print(f"Model accuracy test set with {i} estimators : {clf.score(x_test, y_test)*100:.2f}%")

#6. Save model and load it
import pickle 
pickle.dump(clf, open("../../models/random-forest-model-1.pkl","wb"))

loaded_model = pickle.load(open("../../models/random-forest-model-1.pkl", "rb"))
loaded_model.score(x_test,y_test)

loaded_model.predict(x_test)

              precision    recall  f1-score   support

           0       0.84      0.77      0.81        35
           1       0.72      0.81      0.76        26

    accuracy                           0.79        61
   macro avg       0.78      0.79      0.78        61
weighted avg       0.79      0.79      0.79        61

Model accuracy test set with 10 estimators : 81.97%
Model accuracy test set with 20 estimators : 81.97%
Model accuracy test set with 30 estimators : 81.97%
Model accuracy test set with 40 estimators : 80.33%
Model accuracy test set with 50 estimators : 81.97%
Model accuracy test set with 60 estimators : 80.33%
Model accuracy test set with 70 estimators : 78.69%
Model accuracy test set with 80 estimators : 78.69%
Model accuracy test set with 90 estimators : 77.05%


array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1])