# 3. Fit the model/ algorithm on out data and us it  to make predictions

In [20]:
import numpy as np
import pandas as pd

### 3.1 Fitting the model data

`x` = fetures,  features variables

`y` = labels, targets, target variables

In [21]:
heart_disease = pd.read_csv("../../data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [22]:
# Let's try Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
x = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

np.random.seed(42)
#Split data into trainning and test set
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)

# Instantiate RandomForestClassifier model
clf = RandomForestClassifier()
# Fit the model (trainning machine learning model)
clf.fit(x_train,y_train)

# Evaluate model (use  the pattenrn of the model has learned)
clf.score(x_test, y_test)

0.8524590163934426

In [23]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### 3.2 Make predictions using machine learning model
2 methods to make predictions : 
   1. `predict()`
   2. `predict_proba()`

In [24]:
# Use a trained model to make prediction
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [25]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [26]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(x_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [27]:
# Evaluate model (use  the pattenrn of the model has learned)
clf.score(x_test, y_test)

0.8524590163934426

In [28]:
from sklearn.metrics import confusion_matrix ,accuracy_score
print(accuracy_score(y_preds, y_test))
print(pd.DataFrame(confusion_matrix(y_test, y_preds), columns=["Actual_0","Actual_1"], index=["Predict_0","Predict_1"]) )

0.8524590163934426
           Actual_0  Actual_1
Predict_0        24         5
Predict_1         4        28


In [29]:
# make predictions with predict_proba()
y_preds_proba = clf.predict_proba(x_test)
y_preds_proba[:5]

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [30]:
np.array(y_test[:5])

array([0, 0, 1, 0, 1])

#### Making prediction with regression model

In [31]:
# Import Boston housing in datasets
from sklearn.datasets import load_boston
boston = load_boston()
boston;

In [32]:
boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"] = boston["target"]
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [33]:
# Let's try Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Create data
x = boston_df.drop("target",axis=1)
y = boston_df["target"]

x_train,x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)

# Instantate Random Forest model
clf = RandomForestRegressor()
clf.fit(x_train,y_train)
# Check the score of the model
clf.score(x_test,y_test)

0.8654448653350507

In [34]:
y_preds = clf.predict(x_test)
y_preds

array([23.081, 30.574, 16.759, 23.46 , 16.893, 21.644, 19.113, 15.334,
       21.14 , 20.639, 19.787, 19.541,  8.583, 21.85 , 19.531, 25.851,
       19.759,  8.22 , 45.109, 14.712, 24.548, 23.956, 14.548, 22.944,
       15.023, 14.643, 21.137, 14.153, 19.232, 20.666, 19.588, 23.254,
       33.01 , 20.461, 14.271, 15.889, 34.704, 19.154, 20.85 , 24.395,
       18.978, 29.84 , 45.302, 19.447, 22.234, 13.751, 15.511, 24.612,
       18.729, 28.235, 21.21 , 34.218, 17.271, 26.147, 45.279, 21.924,
       15.532, 32.412, 22.212, 20.453, 25.532, 34.326, 28.795, 18.951,
       27.145, 17.181, 13.534, 23.04 , 28.714, 15.802, 20.451, 27.87 ,
       10.193, 21.507, 22.383,  7.265, 20.089, 45.388, 10.88 , 13.053,
       21.322, 12.366, 20.233,  9.135, 20.052, 26.787, 15.277, 23.267,
       23.613, 17.699, 21.617,  7.921, 19.475, 18.807, 22.386, 19.836,
       38.714, 13.159, 12.476, 13.612, 20.205, 23.832])

In [35]:
# Compare the prediction to truth label
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

2.136382352941176